export const protronicsStates = {
	arlington: 'Arlington, VA',
	atlanta: 'Atlanta, GA',
	austin: 'Austin, TX',
	baltimore: 'Baltimore, MD',
	boston: 'Boston, MA',
	chicago: 'Chicago, IL',
	columbia: 'Columbia, SC',
	hillsborough: 'Hillsborough, OR',
	houston: 'Houston, TX',
	'new-jersey': 'New Jersey, NJ',
	'new-york': 'New York, NY',
	ohio: 'Ohio, MI',
	raleigh: 'Raleigh, NC',
	'san-jose': 'San Jose, CA',
	tampa: 'Tampa, FL',
	tennessee: 'Nashville, TN',
	washington: 'Washington, D.C',
  knightdale: 'Knightdale, NC',
	charlotte: 'Charlotte, NC',
};
